### ISSUE TITLE
Hacktoberfest-Update readme.md

### ISSUE THREAD

**Issue by SayantaniDeb** [ProgrammerGaurav/programmergaurav.github.io#26]
# Welcome, to my personal portfolio page.
![issues](https://img.shields.io/github/issues/ProgrammerGaurav/programmergaurav.github.io)
![Forks](https://img.shields.io/github/forks/ProgrammerGaurav/programmergaurav.github.io)
![Stars](https://img.shields.io/github/stars/ProgrammerGaurav/programmergaurav.github.io)
![connect](https://img.shields.io/twitter/url?url=https%3A%2F%2Fgithub.com%2FProgrammerGaurav%2Fprogrammergaurav.github.io)
          

## Table of contents

* [Technolgies used](#the-technologies-used-are)
* [Website-Images](#images)
* [Website-link](https://programmergaurav.github.io/)

## The technologies used are: 

* HTML
* SCSS
* JavaScript

## Images

| Content        | Snapshot           | 
| ------------- |:-------------:| 
| Home page      | ![image](https://user-images.githubusercontent.com/74983536/135504333-19514077-185e-427a-8466-530c92c65378.png) | 
| About      | ![image](https://user-images.githubusercontent.com/74983536/135504531-bf8e9e0b-c98d-486e-875d-d7e25d03c638.png) | 
| Skills | ![image](https://user-images.githubusercontent.com/74983536/135504665-514eb6e0-ad3f-40a2-8c0c-20a7922d34a7.png) |   
| Work |  ![image](https://user-images.githubusercontent.com/74983536/135504782-d95a1b4b-3e0f-4312-a536-4a090499c5b9.png) |
| Activity chart | ![image](https://user-images.githubusercontent.com/74983536/135504893-8626adb4-5fe9-42e1-8a51-ff21c61cbf95.png) |
| Contact | ![image](https://user-images.githubusercontent.com/74983536/135505181-b9f5e292-df42-454f-9983-9a576e395442.png) |

**Comment by SayantaniDeb** [comment]
Please assign me to make these changes.

**Comment by fakeshkol** [comment]
Please assign me this

**Comment by bikramruj99** [comment]
please assign me to make the website more attractive , beautiful and SEO friendly.
