### ISSUE TITLE
Regarding hacktoberfest!

### ISSUE THREAD

**Issue by ShahinaShanu** [ProgrammerGaurav/programmergaurav.github.io#5]
Thanks for accepted as hacktoberfest label. Can you please merge my PR, if you accepted as hacktoberfest. If have you any query or any improvement regarding made changes in Readme and index file, reply me soon.

**Comment by ProgrammerGaurav** [comment]
> Thanks for accepted as hacktoberfest label. Can you please merge my PR, if you accepted as hacktoberfest. If have you any query or any improvement regarding made changes in Readme and index file, reply me soon.

I have added hacktoberfest-accepted label which will allow your pull request to be accepted in hacktoberfest

**Comment by ShahinaShanu** [comment]
That's fine..but you didn't close the pull request that's why I asked and I
am a beginner on this platform to learn..Thanks for informed me.

**Comment by ProgrammerGaurav** [comment]
Yeah sure, but the changes are not good enough for merging, This is my Personal Opinion. So I am really Sorry, I am not going to merge your PR

**Comment by ShahinaShanu** [comment]
It's okay.. don't feel sorry..I need to more work for open source projects
and thanks to clearance again.
